#!/usr/bin/env bash
# Update package lists and upgrade existing packages
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install nginx -y

# Create a backup of the default Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Modify the Nginx configuration file to include the new redirect URL
sudo sed -i '/server_name _;/a \ \ \ \ location /redirect_me {\n \ \ \ \ \ \ \ \ return 301 https://youtu.be/kyqpSycLASY;\n \ \ \ \ }' /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply the changes
sudo systemctl restart nginx
